name: iOS SDK Release
run-name: ${{ github.actor }} is starting iOS SDK release

on:
  workflow_dispatch:
    inputs:
      version_number:
        description: "iOS SDK version"
        required: true
      branch:
        description: "Branch to release (defaults to master)"
        required: true
        default: "master"
      changelog_section:
        description: "Changelog version header (e.g. 6.4.17, 6.5.0-beta)"
        required: true
      set_prerelease:
        type: boolean
        description: "Is this a prerelease?"
        default: false
env:
  VERSION: ${{ github.event.inputs.version_number }}
  BRANCH: ${{ github.event.inputs.branch }}
  CHANGELOG_SECTION: ${{ github.event.inputs.changelog_section }}
  OUTPUT_DIR: ./output_dir
  GITHUB_TOKEN: ${{ secrets.SDK_RELEASE_TOKEN }}
  RELEASE_BRANCH:
  SET_PRERELEASE: ${{ github.event.inputs.set_prerelease }}
  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
  COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}

jobs:
  ios-sdk-release:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"
          bundler-cache: true
      - name: Install Cocoapods
        run: gem install cocoapods

      - name: set version number and push podspecs to git
        run: bundle exec fastlane ios bump_release_version version:$VERSION

      - name: clean cocaopods cache and lint
        run: bundle exec fastlane ios clean_and_lint

      - name: create xcframeworks and zip
        run: bundle exec fastlane ios build_xcframework output_dir:./output_dir

      - name: create github release and upload assets

        run: |
          bundle exec fastlane ios create_release version:$VERSION branch:$BRANCH changelog_section:$CHANGELOG_SECTION output_dir:$OUTPUT_DIR github_token:$GITHUB_TOKEN set_prerelease:$SET_PRERELEASE

      - name: push pods to trunk
        run: bundle exec fastlane ios pod_trunk_push

      - name: slack notification
        run: bundle exec fastlane ios slack_message version:$VERSION changelog_section:$CHANGELOG_SECTION slack_webhook:$SLACK_WEBHOOK
